### ISSUE TITLE
Switch from JPM to WebExt

### ISSUE THREAD

**Issue by pdehaan** [dequelabs/axe-firefox-devtools#53]
I'm using Firefox 57 (Nightly), but it isn't letting me install the aXe Developer Tools add-on because it is incompatible w/ the latest Firefox.

<img width="1001" alt="axe_developer_tools____add-ons_for_firefox" src="https://user-images.githubusercontent.com/557895/29949449-a8b01b50-8e69-11e7-816a-9f38e9bab6dc.png">

**Figure 1:** Trying to install via addons.mozilla.org.

---

<img width="396" alt="add-ons_manager" src="https://user-images.githubusercontent.com/557895/29949477-f0f78dee-8e69-11e7-8718-8692c9dd7e0f.png">

**Figure 2:** Trying to install manually via about:addons.

---

<img width="661" alt="blank_skitch_document" src="https://user-images.githubusercontent.com/557895/29949420-7400c102-8e69-11e7-9da9-bcd5fc3d3b26.png">

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by WilcoFiers** [comment]
Hi @pdehaan Thanks for the heads up. I'm not surprised. We've known that Mozilla will be switching over to a new extension model for some time now. Unfortunately it's taking until Firefox 55 to get all the APIs in place that we could make the web extensions work.

We have a web extension implementation for Chrome, and are currently in the process of making it work with Firefox as well. It'll probably be a few more weeks before we can release, but it's on its way, and should be done well before Firefox 57 is released. In the mean time, you may want to check out the [Chrome extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) to see what's coming your way very soon. It's got some great features that we haven't been able to release to Firefox because of this whole extension API change thing.

**Comment by marcysutton** [comment]
Also it does still work in Firefox 55 if you use "download anyway" and install the XPI through about://addons.

**Comment by NickWilde1990** [comment]
Any updates on this/plan in place?

**Comment by WilcoFiers** [comment]
@NickWilde1990 Yep :) We had it come back from QA on Friday. We have a few things to fix. Not much longer now!

**Comment by NickWilde1990** [comment]
Great! @WilcoFiers I've got a FF Nightly as my primary with a few backups options; so if you want testers I'm interested and ahem don't mind danger. Been a few years since I did any FF extension dev so not familiar with the new format but I'm sure I could still build etc. I looked and didn't see any commits here (or a branch) otherwise, I'd already be trying it out ;)

**Comment by WilcoFiers** [comment]
Yeah, it's a complete rebuild. We're probably not going to open source it, since it builds on some internal projects.
