### ISSUE TITLE
What's the license of Axe?

### ISSUE THREAD

**Issue by dannycolin** [dequelabs/axe-firefox-devtools#61]
Hi,

The about section on addons.mozilla.com said that Axe is Open Source but I can't find
the license. Would it be possible to add a LICENSE file on GitHub?

Best regards,

EDIT:

Nevermind. I find the main repo. The link on the firefox store was wrong. ;)

**Comment by marcysutton** [comment]
As an FYI...the [axe-core](https://github.com/dequelabs/axe-core) JavaScript library is open source, but the extension isn't any longer.

**Comment by dylanb** [comment]
@dannycolin The link on the Firefox store is correct

**Comment by dannycolin** [comment]
May I ask why the extension is no longer open source but the core still is?

**Comment by dylanb** [comment]
@dannycolin The Chrome extension was never open source and the new Firefox extension is based on the Chrome extension's source code

**Comment by WilcoFiers** [comment]
The current Axe extension is a "light" version of the WorldSpace Attest browser extension, which is a commercial product. Before the Attest extension, we actually maintained three extensions in separate code bases, one open (Axe FF) and two closed (FireEyes, Axe Chrome). That was difficult to keep up to date. So when we build Attest we decided to have a single code base from which we can generate separate extensions. Less code, no duplicate work, and nothing can go out of date. The trade-off there was that we'd have to keep it closed, because that code base includes Attest.
