### ISSUE TITLE
JPM compatibility

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-firefox-devtools#9]
The CFX tool is deprecated and has been replaced with the NPM-based [jpm](https://github.com/mozilla/jpm)

See also: https://blog.mozilla.org/addons/2015/02/26/jpm-replaces-cfx-for-firefox-38/

With JPM we could consume the NPM axe-core package.

**Comment by dylanb** [comment]
@dsturley I upgraded to jpm but using the node module directly is not simple because the require only works within the main.js file and we need to find a way to include it in the content scripts. This could be done using CFX but would result in a "node_modules" directory in the XPI.

If we want to make that change, lets make it as part of a separate issue - thoughts?
